---
title: "Math 104A (2022 Fall) - Introduction to numerical analysis"
author: "Jea-Hyun Park"
date: "2022-09-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Syllabus

[Syllabus (Google doc)](https://docs.google.com/document/d/1SYEj8hRaOvg_5h_YQg4tpgn6rFfCK90nyNkxl4EJ8X4/edit?usp=sharing) 

## Course Calendar
[Course Calendar (Google sheet)](https://docs.google.com/spreadsheets/d/1F_sdCRuRNuAO_UI5SutbjAc398I9ITBQfKOXatjHRxI/edit?usp=sharing) 

## Notes/Slides
The slides and board work files are updated by chapter, not by date. Click on any date that covers each chapter.

|        |            |       |
|:------:|:----------:|:-----:|
| Week 0 |            | 09/22 |
|        |            | Ch. 3 Solution of nonlinear equations - Bisection method [Slides](./notes/104ASlides_RootFinding01.pdf), [Board work](./notes/104ABoardWork_RootFinding01.pdf)|
| Week 1 | 09/27      | 09/29 |
|        | Ch. 3 Solution of nonlinear equations - Newton's method [Slides](./notes/104ASlides_RootFinding01.pdf),  [Board work](./notes/104ABoardWork_RootFinding01.pdf)|Ch. 3 Solution of nonlinear equations - Secant method [Slides](./notes/104ASlides_RootFinding01.pdf),  [Board work](./notes/104ABoardWork_RootFinding01.pdf)|  |
| Week 2 | 10/04      | 10/06 |
|        | Ch. 3 Solution of nonlinear equations - Fixed point iteration [Slides](./notes/104ASlides_RootFinding01.pdf),  [Board work](./notes/104ABoardWork_RootFinding01.pdf) | Ch. 6 Approximation - Vandermonde, Newton form [Slides](./notes/104ASlides_Approximation01.pdf),  [Board work](./notes/104ABoardWork_Approximation01.pdf)|
| Week 3 | 10/11      | 10/13 |
|        | Ch. 6 Approximation - Lagrange form, Runge's phenomenon [Slides](./notes/104ASlides_Approximation01.pdf),  [Board work](./notes/104ABoardWork_Approximation01.pdf) | Ch. 6 Approximation - Chebyshev polynomials [Slides](./notes/104ASlides_Approximation01.pdf),  [Board work](./notes/104ABoardWork_Approximation01.pdf)|
| Week 4 | 10/18      | 10/20 |
|        | Ch. 6 Approximation - Chebychev polynomials, Divided differences [Slides](./notes/104ASlides_Approximation01.pdf),  [Board work](./notes/104ABoardWork_Approximation01.pdf) | Ch. 6 Approximation - Divided differences, Computational HW1 review [Slides](./notes/104ASlides_Approximation01.pdf),  [Board work](./notes/104ABoardWork_Approximation01.pdf)|
| Week 5 | 10/25      | 10/27 |
|        | Midterm (Ch. 3, 6) | Ch. 7 Numerical differentiation and integration - Numerical differentication [Slides](./notes/104ASlides_NumDiffInt01.pdf),  [Board work](./notes/104ABoardWork_NumDiffInt01.pdf)|
 

