---
title: "Math 104A (2022 Fall) - Introduction to numerical analysis"
author: "Jea-Hyun Park"
date: "2022-09-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Syllabus 

[Syllabus (Google doc)](https://docs.google.com/document/d/1SYEj8hRaOvg_5h_YQg4tpgn6rFfCK90nyNkxl4EJ8X4/edit?usp=sharing) 

## Course Calendar
[Course Calendar (Google sheet)](https://docs.google.com/spreadsheets/d/1F_sdCRuRNuAO_UI5SutbjAc398I9ITBQfKOXatjHRxI/edit?usp=sharing) 

## Notes/Slides
The slides and board work files are updated by chapter, not by date. Click on any date that covers each chapter.

|        |            |       |
|:------:|:----------:|:-----:|
| Week 0 |            | 09/22 |
|        |            | Ch. 3 Solution of nonlinear equations - Bisection method [Slides](./resources/notes/na/104ASlides_RootFinding01.pdf), [Board work](./resources/notes/na/104ABoardWork_RootFinding01.pdf)|
| Week 1 | 09/27      | 09/29 |
|        | Ch. 3 Solution of nonlinear equations - Newton's method [Slides](./resources/notes/na/104ASlides_RootFinding01.pdf),  [Board work](./resources/notes/na/104ABoardWork_RootFinding01.pdf)|Ch. 3 Solution of nonlinear equations - Secant method [Slides](./resources/notes/na/104ASlides_RootFinding01.pdf),  [Board work](./resources/notes/na/104ABoardWork_RootFinding01.pdf)|  |
| Week 2 | 10/04      | 10/06 |
|        | Ch. 3 Solution of nonlinear equations - Fixed point iteration [Slides](./resources/notes/na/104ASlides_RootFinding01.pdf),  [Board work](./resources/notes/na/104ABoardWork_RootFinding01.pdf) | Ch. 6 Approximation - Vandermonde, Newton form [Slides](./resources/notes/na/104ASlides_Approximation01.pdf),  [Board work](./resources/notes/na/104ABoardWork_Approximation01.pdf)|
| Week 3 | 10/11      | 10/13 |
|        | Ch. 6 Approximation - Lagrange form, Runge's phenomenon [Slides](./resources/notes/na/104ASlides_Approximation01.pdf),  [Board work](./resources/notes/na/104ABoardWork_Approximation01.pdf) | Ch. 6 Approximation - Chebyshev polynomials [Slides](./resources/notes/na/104ASlides_Approximation01.pdf),  [Board work](./resources/notes/na/104ABoardWork_Approximation01.pdf)|
| Week 4 | 10/18      | 10/20 |
|        | Ch. 6 Approximation - Chebychev polynomials, Divided differences [Slides](./resources/notes/na/104ASlides_Approximation01.pdf),  [Board work](./resources/notes/na/104ABoardWork_Approximation01.pdf) | Ch. 6 Approximation - Divided differences, Computational HW1 review [Slides](./resources/notes/na/104ASlides_Approximation01.pdf),  [Board work](./resources/notes/na/104ABoardWork_Approximation01.pdf)|
| Week 5 | 10/25      | 10/27 |
|        | Midterm (Ch. 3, 6) | Ch. 7 Numerical differentiation and integration - Numerical differentication [Slides](./resources/notes/na/104ASlides_NumDiffInt01.pdf),  [Board work](./resources/notes/na/104ABoardWork_NumDiffInt01.pdf)|
| Week 6 | 11/01      | 11/3 |
|        | Ch. 7 Numerical differentiation and integration - Newton-Cotes [Slides](./resources/notes/na/104ASlides_NumDiffInt01.pdf),  [Board work](./resources/notes/na/104ABoardWork_NumDiffInt01.pdf) | Ch. 7 Numerical differentiation and integration - Newton-Cotes, Gaussian Quadrature [Slides](./resources/notes/na/104ASlides_NumDiffInt01.pdf),  [Board work](./resources/notes/na/104ABoardWork_NumDiffInt01.pdf)|
| Week 7 | 11/08      | 11/10 |
|        | Ch. 7 Numerical differentiation and integration - Gaussian quadrature [Slides](./resources/notes/na/104ASlides_NumDiffInt01.pdf),  [Board work](./resources/notes/na/104ABoardWork_NumDiffInt01.pdf) | Ch. 8 Numerical methods for ODE - Existence and uniqueness [Slides](./resources/notes/na/104ASlides_NumODE01.pdf),  [Board work](./resources/notes/na/104ABoardWork_NumODE01.pdf)| 
| Week 8 | 11/15      | 11/17 |
|        | Ch. 8 Numerical methods for ODE - Existence and uniqueness, Taylor-series method [Slides](./resources/notes/na/104ASlides_NumODE01.pdf),  [Board work](./resources/notes/na/104ABoardWork_NumODE01.pdf) | Ch. 8 Numerical methods for ODE - Runge-Kutta method [Slides](./resources/notes/na/104ASlides_NumODE01.pdf),  [Board work](./resources/notes/na/104ABoardWork_NumODE01.pdf)| 
| Week 9 | 11/22      | 11/24 |
|        | Ch. 8 Numerical methods for ODE - Linear multistep method [Slides](./resources/notes/na/104ASlides_NumODE01.pdf),  [Board work](./resources/notes/na/104ABoardWork_NumODE01.pdf) | Thanksgiving | 
| Week 10 | 11/29      | 12/01 |
|        | Ch. 8 Numerical methods for ODE - Convergence of linear multistep method [Slides](./resources/notes/na/104ASlides_NumODE01.pdf),  [Board work](./resources/notes/na/104ABoardWork_NumODE01.pdf) | Ch. 8 Numerical methods for ODE - Convergence of linear multistep method [Slides](./resources/notes/na/104ASlides_NumODE01.pdf),  [Board work](./resources/notes/na/104ABoardWork_NumODE01.pdf) | 
<!-- | Week 11 | 12/5      | 12/6,7 |
|        | Special offce hours (10-11am, 1-2pm),  [Computational HW2](./resources/notes/na/ComHW2.pdf),  [Example code](https://colab.research.google.com/drive/1m1hT7a1On1iCazM60mmtGEl7rfTf6guc?usp=sharing), [Discussion on the example code and the result](https://gauchocast.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=8a89358d-1d05-4d3e-878d-af6101720295)| Final exam | 
-->

